// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOVHkXfF986Csx69xLKCSy3GAGtykAdg',
    appId: '1:1006223874439:web:2d68af94d20da1ac345b22',
    messagingSenderId: '1006223874439',
    projectId: 'bks-task',
    authDomain: 'bks-task.firebaseapp.com',
    storageBucket: 'bks-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPgwdg2QBVhkWjjJGkDh2ioxUse5YmDY',
    appId: '1:1006223874439:android:499dd62de64877b9345b22',
    messagingSenderId: '1006223874439',
    projectId: 'bks-task',
    storageBucket: 'bks-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPmGN89zCGKe65SS5OJaN577nIaHAhcSw',
    appId: '1:1006223874439:ios:b864bdc840c38783345b22',
    messagingSenderId: '1006223874439',
    projectId: 'bks-task',
    storageBucket: 'bks-task.appspot.com',
    iosClientId: '1006223874439-6usg1bbjhr833bln1vcagrotcshqs6cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bksCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPmGN89zCGKe65SS5OJaN577nIaHAhcSw',
    appId: '1:1006223874439:ios:b864bdc840c38783345b22',
    messagingSenderId: '1006223874439',
    projectId: 'bks-task',
    storageBucket: 'bks-task.appspot.com',
    iosClientId: '1006223874439-6usg1bbjhr833bln1vcagrotcshqs6cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bksCase',
  );
}
